
"""
Django settings for scanner project.

Generated by 'django-admin startproject' using Django 5.2.14.
"""

from pathlib import Path
import os
from django.core.management.utils import get_random_secret_key

# ==========================================================
# BASE DIRECTORY
# ==========================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# ==========================================================
# SECURITY
# ==========================================================

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or get_random_secret_key()

DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]

# ==========================================================
# APPLICATIONS
# ==========================================================

INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'myapp',
]

# ==========================================================
# MIDDLEWARE
# ==========================================================

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ==========================================================
# URL CONFIGURATION
# ==========================================================

ROOT_URLCONF = 'scanner.urls'

# ==========================================================
# TEMPLATES
# ==========================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [
            BASE_DIR / 'templates'
        ],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ==========================================================
# WSGI
# ==========================================================

WSGI_APPLICATION = 'scanner.wsgi.application'

# ==========================================================
# DATABASE
# ==========================================================

DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.sqlite3',

        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ==========================================================
# CUSTOM USER MODEL
# ==========================================================

AUTH_USER_MODEL = 'myapp.CustomUser'

# ==========================================================
# PASSWORD VALIDATION
# ==========================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME':
            'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ==========================================================
# INTERNATIONALIZATION
# ==========================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

# ==========================================================
# STATIC FILES
# ==========================================================

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# ==========================================================
# MEDIA FILES
# ==========================================================

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'

# ==========================================================
# LOGIN / LOGOUT
# ==========================================================

LOGIN_URL = '/login/'

LOGIN_REDIRECT_URL = '/dashboard/'

LOGOUT_REDIRECT_URL = '/login/'

# ==========================================================
# DEFAULT PRIMARY KEY
# ==========================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==========================================================
# SECURITY HARDENING
# ==========================================================

SECURE_BROWSER_XSS_FILTER = True

SECURE_CONTENT_TYPE_NOSNIFF = True

X_FRAME_OPTIONS = 'DENY'

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

SESSION_COOKIE_HTTPONLY = True

CSRF_COOKIE_HTTPONLY = True

SESSION_COOKIE_AGE = 3600

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# ==========================================================
# AEGIS ENGINE DIRECTORIES
# ==========================================================

REPORT_DIR = BASE_DIR / "reports"

QUARANTINE_DIR = BASE_DIR / "quarantine"

THREAT_DB_DIR = BASE_DIR / "threat_database"

IOC_DIR = BASE_DIR / "ioc_data"

LOG_DIR = BASE_DIR / "logs"

for directory in [

    REPORT_DIR,
    QUARANTINE_DIR,
    THREAT_DB_DIR,
    IOC_DIR,
    LOG_DIR

]:
    os.makedirs(directory, exist_ok=True)

# ==========================================================
# FILE MONITORING
# ==========================================================

MONITORED_DIRECTORIES = [

    str(Path.home() / "Downloads"),

    str(Path.home() / "Desktop"),

    str(Path.home() / "Documents"),
]

# ==========================================================
# THREAT INTELLIGENCE
# ==========================================================

VT_API_KEY = os.environ.get('VT_API_KEY', '')

ABUSEIPDB_API_KEY = os.environ.get('ABUSEIPDB_API_KEY', '')

OTX_API_KEY = os.environ.get('OTX_API_KEY', '')

OPENPHISH_URL = "https://openphish.com/feed.txt"

# ==========================================================
# SECURITY ANALYTICS
# ==========================================================

MAX_RISK_SCORE = 100

CRITICAL_THRESHOLD = 90

HIGH_THRESHOLD = 70

MEDIUM_THRESHOLD = 40

LOW_THRESHOLD = 20

# ==========================================================
# FILE INTEGRITY MONITORING
# ==========================================================

FIM_HASH_ALGORITHM = "sha256"

FIM_BASELINE_FILE = (
    BASE_DIR / "fim_baseline.json"
)

# ==========================================================
# MITRE ATT&CK
# ==========================================================

ENABLE_MITRE_MAPPING = True

MITRE_ATTACK_VERSION = "15"

# ==========================================================
# IOC CORRELATION
# ==========================================================

ENABLE_IOC_CORRELATION = True

IOC_MATCH_THRESHOLD = 80

# ==========================================================
# INCIDENT MANAGEMENT
# ==========================================================

AUTO_CREATE_INCIDENTS = True

AUTO_QUARANTINE_CRITICAL = True

AUTO_CLOSE_RESOLVED_INCIDENTS = False

# ==========================================================
# TIMELINE
# ==========================================================

TIMELINE_RETENTION_DAYS = 90

# ==========================================================
# YARA RULES
# ==========================================================

YARA_RULES_DIR = BASE_DIR / "yara_rules"

os.makedirs(
    YARA_RULES_DIR,
    exist_ok=True
)

# ==========================================================
# SIGMA RULES
# ==========================================================

SIGMA_RULES_DIR = BASE_DIR / "sigma_rules"

os.makedirs(
    SIGMA_RULES_DIR,
    exist_ok=True
)

# ==========================================================
# EVENT LOG ANALYSIS
# ==========================================================

ENABLE_EVENT_LOG_ANALYSIS = True

# ==========================================================
# LOGGING
# ==========================================================

LOGGING = {

    'version': 1,

    'disable_existing_loggers': False,

    'handlers': {

        'file': {

            'level': 'INFO',

            'class': 'logging.FileHandler',

            'filename':
                BASE_DIR / 'logs' / 'aegis.log',
        },

        'console': {

            'class':
                'logging.StreamHandler',
        },
    },

    'root': {

        'handlers': [
            'console',
            'file'
        ],

        'level': 'INFO',
    },
}
